[project]
name = "schroedinger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JackApfel", email = "jack.apfel_dev@pm.me" }
]
requires-python = ">=3.14"
dependencies = [
    "discord-py>=2.7.1",
    "dotenv>=0.9.9",
    "mcstatus>=14.2.0",
    "python-a2s>=1.4.2",
]

[project.scripts]
schroedinger = "schroedinger:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
